### PR TITLE
Update setup.py

### PR DESCRIPTION
**Pull request by devxpy**
A setup.py for humans 
https://github.com/kennethreitz/setup.py

This makes it easier for uploading to pypi

NOTE: You might want to change stuff like python version, I am not aware of compatibility

### CODE REVIEW

**Comment by devxpy** [comment]
Okay, have a look/

**Comment by frmdstryr** [comment]
It requires python >=2.7.

Also the url should point to this repo.

**Comment by frmdstryr** [comment]
Looks good, thank you!

**Comment by frmdstryr** [comment]
Uploaded to pypi, thanks!

**Comment by devxpy** [comment]
likewise!

**Pull request merged**
